<a href="https://colab.research.google.com/github/anniewanjohi/SemProject_MLEngine/blob/main/Resume_Job_Fit_Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install datasets pandas -q

In [2]:
from datasets import load_dataset
import pandas as pd

dataset = load_dataset("cnamuangtoun/resume-job-description-fit")
df = dataset["train"].to_pandas()
df.head()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

train.csv: reconstructing file:   0%|          |  0.00B / 53.4MB

train.csv: downloading bytes:           |  0.00B

test.csv: reconstructing file:   0%|          |  0.00B / 15.2MB

test.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/6241 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1759 [00:00<?, ? examples/s]

,resume_text,job_description_text,label
0,SummaryHighly motivated Sales Associate with e...,Net2Source Inc. is an award-winning total work...,No Fit
1,Professional SummaryCurrently working with Cat...,At Salas OBrien we tell our clients that were ...,No Fit
2,SummaryI started my construction career in Jun...,Schweitzer Engineering Laboratories (SEL) Infr...,No Fit
3,SummaryCertified Electrical Foremanwith thirte...,"Mizick Miller & Company, Inc. is looking for a...",No Fit
4,SummaryWith extensive experience in business/r...,Life at Capgemini\nCapgemini supports all aspe...,No Fit

In [3]:
## a. How many rows and columns are contained in the dataset?

In [4]:
df.shape

(6241, 3)

In [5]:
## b. What datatypes are contained in the dataset?

In [6]:
df.dtypes

resume_text             object
job_description_text    object
label                   object
dtype: object

In [7]:
## c. Is the dataset complete? (no missing values)

In [8]:
df.isnull().sum()

resume_text             0
job_description_text    0
label                   0
dtype: int64

In [9]:
## d. Slice first 15 and last 20 rows into df_sample

In [11]:
df_sample = pd.concat([df.head(15), df.tail(20)], ignore_index=True)

In [12]:
df_sample

,resume_text,job_description_text,label
0,SummaryHighly motivated Sales Associate with e...,Net2Source Inc. is an award-winning total work...,No Fit
1,Professional SummaryCurrently working with Cat...,At Salas OBrien we tell our clients that were ...,No Fit
2,SummaryI started my construction career in Jun...,Schweitzer Engineering Laboratories (SEL) Infr...,No Fit
3,SummaryCertified Electrical Foremanwith thirte...,"Mizick Miller & Company, Inc. is looking for a...",No Fit
4,SummaryWith extensive experience in business/r...,Life at Capgemini\nCapgemini supports all aspe...,No Fit
5,"SummarySolution-oriented, results-driven strat...",\n\nResponsibilitiesLead and provide day-to-da...,No Fit
6,SummaryA position in a company that will utili...,"Senior Salesforce Software Engineer, Salesforc...",No Fit
7,SummaryTo participate as a team member in a dy...,***W2 ONLY** \nSoftware Engineer (12-month con...,No Fit
8,SummaryMore than ten years of progressive expe...,Calling all innovators find your future at Fi...,No Fit
9,SummaryCERTIFIED SOFTWARE DEVELOPMENT PROFESSI...,Who We AreWere reinventing the egg protein bus...,No Fit
10,SummaryI have studied Electrical Engineering w...,"At Farmer Brothers, Sales Tax Accountant will ...",No Fit
11,"ExperienceData, Research & Marketing Consultan...",Business Analyst Location: Remote.Duration: 12...,No Fit
12,Professional SummaryHighly motivated Sales Ass...,Job SummaryWe are looking for a Business Analy...,No Fit
13,Professional SummaryDetail-driven accounting p...,Note: By applying to this position you will ha...,No Fit
14,SummaryISTQB certified QA Test Analyst/Payment...,Who We AreWere reinventing the egg protein bus...,No Fit
15,"SummaryHonest, reliable, dependable, hardworki...",Job Purpose: Perform designated tasks in the a...,Good Fit
16,SummarySoftware engineer with 13 years program...,Centurion Consulting Group is looking for a So...,Good Fit
17,SummaryHighly motivated Sales Associate with e...,Skills - Cucumber BDD + Selenium UI Automation...,Good Fit
18,Career OverviewTo obtain a challenging positio...,Who We Are\nApex Fintech Solutions (AFS) power...,Good Fit
19,SummaryTo seek employment as a Project Enginee...,ARM GROUP is looking for a Senior Electrical E...,Good Fit
20,Professional ProfileHighly motivated Sales Ass...,Job Description\nOracle is seeking an experien...,Good Fit
21,ProfileSoftware Test Engineer with two years o...,Lead Software Developer New York City - Hybr...,Good Fit
22,"SummaryJessica, is highly skilled, accomplishe...",#Dynamics365 #ERP # Dynamics365ERP #SupplyChai...,Good Fit
23,SummaryHighly motivated Sales Associate with e...,Role: Senior Software Engineer\nType: Full-Tim...,Good Fit
24,SummaryI am a detail-oriented professional see...,Vaco has a client in Allentown that is looking...,Good Fit
25,Professional SummaryEnthusiastic computer engi...,"Title: Business AnalystLocation: Santa Clara, ...",Good Fit
26,HighlightsProficient inObjective - CJavaC/C++P...,Job Description\nOracle is seeking an experien...,Good Fit
27,SummaryProactive BI Developer/Data Analyst wit...,Business Analyst Location: Remote.Duration: 12...,Good Fit
28,"Summarytyee\nHighlightsMicrosoft Excel, Word, ...","Reviews, analyzes, and evaluates business syst...",Good Fit
29,Summary5+ years of professional experience in ...,Solstice Consulting Group is seeking a Senior ...,Good Fit
30,SummaryResults-driven Data Entry Clerk with ex...,"Hi,\nHope you are doing great today. Please fi...",Good Fit
31,Professional SummaryWith the attitude of learn...,Job Title: DHT - Front End Software Engineer W...,Good Fit
32,Summary• \nOver\nThree years of extensi...,LHH Recruitment Solutions is looking for a Sof...,Good Fit
33,ProfileAbility to prioritize and multi-task in...,Our client is a growing Medical Device company...,Good Fit
34,SummaryFull stack Software Engineer with 8+ ye...,Robert Half is looking for a Senior Full Stack...,Good Fit